version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama2
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - diamond-network

  ollama-init:
    image: ollama/ollama
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: ["sh", "-c", "sleep 10 && OLLAMA_HOST=http://ollama:11434 ollama pull llama3.1:latest"]
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - diamond-network

  diamond-agent:
    build: .
    container_name: diamond-agent
    depends_on:
      - ollama
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - diamond-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-docker
    depends_on:
      - diamond-agent
    ports:
      - "3001:8080"
    env_file:
      - webui.env
    volumes:
      - open_webui_data:/app/backend/data
    restart: unless-stopped
    networks:
      - diamond-network

volumes:
  ollama_data:
  open_webui_data:

networks:
  diamond-network:
    driver: bridge